export enum ModalsActionTypes {
    TOGGLE_OPENED_REGISTRATION_MODAL='TOGGLE_OPENED_REGISTRATION_MODAL',
    TOGGLE_OPENED_LOGIN_MODAL='TOGGLE_OPENED_LOGIN_MODAL',
    OPEN_LOGIN_MODAL='OPEN_LOGIN_MODAL',
    OPEN_REGISTRATION_MODAL='OPEN_REGISTRATION_MODAL'
}

export interface ModalsAction {
    type:ModalsActionTypes,
}